MMORPG/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include
from django.views.generic import RedirectView

import notice

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/ad/profile', permanent=False), name='profile'),
    path('accounts/', include('allauth.urls')),
    path('pages', include('django.contrib.flatpages.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ad/', include('notice.urls')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse_lazy


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Ad(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    heading = models.CharField(max_length=255, unique=True)
    text = RichTextUploadingField()
    time_in = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.heading
    def get_absolute_url(self):
        return reverse_lazy('ad_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'

class Comment(models.Model):
    STATUS_CHOICES = (("pending","на рассмотрении"),("accept","принят"),("reject","отклонен"))
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    time_create = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")

    def __str__(self):
        return self.text[:25]
    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

class UserCode(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    code = models.CharField(max_length=255, null=True, blank=True)



class News(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

templates/ad/ad_create.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Добавить объявление
{% endblock title %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {{form.media}}
    <input type="submit" value="Добавить">

</form>
{% endblock content %}

templates/ad/ad_detail.html
{% extends 'flatpages/default.html' %}

{% block title %}
    {{ad.heading}}
{% endblock title %}

{% block content %}

<div style="margin-bottom: 20px;"> <!-- Добавляем отступ внизу -->
    <h2>{{ad.heading}}</h2>
</div>

<!-- Основное содержание объявления -->
<div style="display: flex; align-items: flex-start;">
    <div style="flex: 1; margin-right: 10px;">
        <!-- Автор и отзывы -->
        <div style="display: flex; flex-direction: column; align-items: flex-start;">
            <p style="font-size: 1.5em;"><strong>Автор:</strong> {{ad.user}}</p>

        </div>
    </div>
    <div style="flex: 3;">
        <!-- Текст объявления -->
        <p>{{ad.text|safe}}</p>
    </div>
</div>


<h3>Добавить отклик</h3>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Оставить">
</form>
<br>

<div style="display: flex; flex-direction: column;">
    {% if ad.comment_set.all %}
        {% for comment in ad.comment_set.all %}
        <div style="display: flex; align-items: flex-start; margin-bottom: 10px;">
            <div style="flex: 1; margin-right: 10px;">
                <p style="font-size: 1.5em;"><strong>Автор:</strong> {{comment.user}}</p>
            </div>
            <div style="flex: 3;">
                <p style="font-size: 1.5em;">{{comment.text}}</p>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h4>Откликов пока нет</h4>
    {% endif %}
</div>

{% endblock content %}

templates/ad/ad_edit.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Добавить объявление
{% endblock title %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {{form.media}}
    <input type="submit" value="Добавить">

</form>
{% endblock content %}

templates/ad/ad_list.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Все объявления
{% endblock title %}

{% block content %}

<div style="margin-bottom: 20px;"> <!-- Добавляем отступ внизу -->
    <h2>Все объявления</h2>
</div>

<!-- Объявления выводятся в отдельных блоках -->
{% for ad in ads %}
<div style="border-top: 1px solid #ccc; padding: 10px; margin-bottom: 20px;">
    <!-- Заголовок объявления -->
    <h3 style="margin-bottom: 10px;">{{ad.heading}}</h3>

    <!-- Основное содержание объявления -->
    <div style="display: flex; align-items: flex-start;">
        <div style="flex: 1; margin-right: 10px;">
            <!-- Автор и отзывы -->
            <div style="display: flex; flex-direction: column; align-items: flex-start;">
                <p style="font-size: 1.5em;"><strong>Автор:</strong> {{ad.user}}</p>
            </div>
        </div>
        <div style="flex: 3;">
            <!-- Текст объявления -->
            <p>{{ad.text|safe}}</p>
        </div>
    </div>
    <!-- Дата создания и кнопки -->
    <div style="display: flex; justify-content: space-between; align-items: center;">
        <p style="font-size: 1.5em;">{{ad.time_in|date:"d.m.Y"}}</p>
        <div>
            <a href="{% url 'ad_detail' pk=ad.id %}" class="btn btn-primary">Отклики</a>
            {% if request.user.is_authenticated and request.user == ad.user %}
            <a href="{% url 'ad_edit' pk=ad.id %}" class="btn btn-secondary">Редактировать</a>
            {% endif %}
        </div>
    </div>
</div>
{% empty %}
<p>Объявлений пока нет.</p>
{% endfor %}

{% if page_obj.has_previous %}
   <a href="?page=1">1</a>
   {% if page_obj.previous_page_number != 1 %}
       ...
       <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
   {% endif %}
{% endif %}

<!-- Информация о текущей странице -->
{{ page_obj.number }}

<!-- Информация о следующих страницах -->
{% if page_obj.has_next %}
   <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
   {% if paginator.num_pages != page_obj.next_page_number %}
       ...
       <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
   {% endif %}
{% endif %}

{% endblock content %}

templates/ad/code_error.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Неверный код активации
{% endblock title %}

{% block content %}

<h3>Вы ввели не верный код активации {{code}}</h3>
  <a class="btn btn-outline-danger btn-sm" href="{% url 'account_inactive' %}">повторите ввод кода</a>
{% endblock content %}

templates/ad/profile.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Профиль
{% endblock title %}

{% block content %}

<h2 style="color: orange;">Страничка пользователя  {{user.username}}</h2>
<h3>Отклики на мои объявления</h3>

<div style="display: flex; justify-content: flex-end; margin-bottom: 20px;">
    <form action="" method="get">
        {{ filter.form.as_p }}
        <input style="font-size: 0.8em; float: right;" type="submit" value="Применить">
    </form>
</div>

<div style="display: flex; flex-direction: column;">
    {% for comment in comments %}
    <div style="display: flex; align-items: flex-start; margin-bottom: 10px;">
        <div style="flex: 1; margin-right: 10px;">
            <p style="font-size: 1.5em;text-align: left;"><strong style="color: black;">Автор:</strong> <span style="color: red;">{{comment.user}}</span></p>
        </div>
        <div style="flex: 3;">
            <p style="font-size: 1.5em;">{{comment.text}}</p>
        </div>
        <div style="flex: 1;">
            <p style="font-size: 1.5em;">
                {% if comment.status == 'accept' %}
                    <span style="color: green;">Принят</span>
                {% elif comment.status == 'reject' %}
                    <span style="color: red;">Отклонен</span>
                {% else %}
                    {{comment.get_status_display}}
                {% endif %}
            </p>
            {% if comment.status == 'pending' %}
            <a href="{% url 'comment_accept' comment.id %}" class="btn btn-success btn-sm">Принять</a>
            <a href="{% url 'comment_reject' comment.id %}" class="btn btn-danger btn-sm">Отклонить</a>
            {% endif %}
        </div>
    </div>
    <!-- Дата создания отклика -->
    <p style="font-size: 1.5em;text-align: left; color: blue;">{{comment.time_create|date:"d.m.Y"}}</p>
    {% endfor %}
</div>

{% endblock content %}